### ISSUE TITLE
Implement a PoC of the ZK On-chain Light Client

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/wisp#1]
The node will be a backend server that is assigned "work" to produce proof and update the state of the light client contract on-chain. It should contain 2 docker images. One for the "master" who accepts proofs from an API and one for the "prover" who will execute the proof once requested.

**Node**
- [x] Must have a REST API endpoint at `/api/v1/proofs/` that contains the `slot` number for which proof must be generated. Once called, the server will add the job of creating proof for the specific slot into a queue and return information on the request for proof such as `slot` and `status`. If the prover is not creating proofs, he is assigned the work and will start producing the proof.
- [x] Must have a REST API endpoint for querying proofs at `/api/v1/proofs/{ID}`. Once queried, the server will return the latest information for the requested proof. Data will comprise of `slot` (number), `status` (`INITIAL`, `PROOF_GENERATION`, `TX_SUBMITTED`, `SUCCESSFUL`), `transactionHash` (hash of the tx that submitted the proof), `proof` (the actual proof).
- [x] The node must prepare 

**Prover**
TODO
